version: "3.7"
services:
  #Laravel Service
  app:
    container_name: job_portal_laravel_react
    restart: always
    tty: true
    working_dir: /var/www/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: "idekey=IDE_DEBUG"
      PHP_IDE_CONFIG: "serverName=job_portal_laravel_react"
    #    ports:
    #      - 9001:9000
    #      - 9002:9001
    volumes:
      - .:/var/www/app
    depends_on:
      - database
    links:
      - database
    networks:
      - job_portal_network

  #DB Service
  database:
    image: mariadb:latest
    container_name: job_portal_database
    restart: always
    working_dir: /etc/mysql
    tty: true
    environment:
      MYSQL_DATABASE: job_portal
      MYSQL_USER: job_portal
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
    ports:
      - 3333:3306
#    volumes:
#      - ./.docker/db/dump.sql:/docker-entrypoint-initdb.d/dump  .sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - job_portal_network

  #Nginx Service
  server:
    image: nginx:alpine
    container_name: job_portal_server
    restart: always
    tty: true
    ports:
      - 8100:8080
    volumes:
      - .:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    networks:
      - job_portal_network

#Docker Networks
networks:
  job_portal_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
